作業目標:<br>
1. 熟悉索引操作
2. 分辨合併資料方法使用時機

作業重點:<br>
1. 操作索引注意有分loc、iloc<br>
2. 合併資料方法concat、merge、join其中有參數可以調整inner或outer

題目:<br>
讀取STOCK_DAY_0050_202009.csv串聯STOCK_DAY_0050_202010.csv，並且找出open小於close的資料

In [ ]:
import pandas as pd

In [ ]:
#讀取STOCK_DAY_0050_202009.csv、STOCK_DAY_0050_202010.csv
stock1 = pd.read_csv('STOCK_DAY_0050_202009.csv')
stock2 = pd.read_csv('STOCK_DAY_0050_202010.csv')

In [ ]:
#串聯
stock_data = pd.concat([stock1,stock2])

In [ ]:
#找出open小於close的資料
stock_data[stock_data.open<stock_data.close]

         date    open    high     low   close
0   109/09/01  102.45  103.35  101.85  103.35
3   109/09/04  102.00  102.70  101.90  102.55
5   109/09/08  102.75  103.10  102.45  103.00
6   109/09/09  101.75  102.35  101.15  102.30
7   109/09/10  102.80  103.35  102.60  103.20
8   109/09/11  103.20  103.35  102.80  103.25
9   109/09/14  103.50  104.55  103.25  104.55
10  109/09/15  104.45  105.20  104.25  104.95
19  109/09/28  101.35  102.30  101.00  102.30
21  109/09/30  102.75  103.45  102.60  103.00
1   109/10/06  104.00  104.35  103.85  104.25
2   109/10/07  104.00  105.00  103.50  104.80
3   109/10/08  105.45  106.35  105.30  106.20
4   109/10/12  106.70  107.70  106.70  107.05
9   109/10/19  105.65  106.60  105.60  106.60
12  109/10/22  105.70  106.10  105.50  106.10

# [作業目標]

1. [簡答題] 請問下列四種不同的 DataFrame 選取結果有什麼差異？

```
df.loc[ '2013-01-01', 'A'] 
df.loc[ '2013-01-01', ['A', 'B'] ] 
df.loc[ '2013-01-01':'2013-01-02', 'A' ] 
df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] 
```


2. 請根據提供的資料，選擇出下列的要求：

```
# - select the first 3 rows.
# - select the odd rows. (index = 1, 3, 5)
# - select the last 2 columns.
# - select the even columns. (index = 0, 2, 4)
```

3. 請根據提供的資料，選擇出下列的要求：

```
# - 1. filtered by first column > 20?
# - 2. filtered by first column + second column > 50
# - 3. filtered by first column < 30 or second column > 30
# - 4. filtered by total sum of row > 100
```

# 作業

### 1. [簡答題] 請問下列四種不同的 DataFrame 選取結果有什麼差異？

```
df.loc[ '2013-01-01', 'A'] 
df.loc[ '2013-01-01', ['A', 'B'] ] 
df.loc[ '2013-01-01':'2013-01-02', 'A' ] 
df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] 
```

### 2. 請根據提供的資料，選擇出下列的要求：

```
# - select the first 3 rows.
# - select the odd rows. (index = 1, 3, 5)
# - select the last 2 columns.
# - select the even columns. (index = 0, 2, 4)
```

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
df

In [ ]:
# Answer

# - select the first 3 rows.
df[0:3]
df.iloc[0:3,:]
df.iloc[0:3]

# - select the odd rows. (index = 1, 3, 5)
df[1::2]
df.iloc[1::2, :]
df.iloc[[1,3,5], :]

# - select the last 2 columns.
df.iloc[:, -2:]

# - select the even columns. (index = 0, 2)
df.iloc[:, 0::2]
df.iloc[:, [0, 2]]

### 3. 請根據提供的資料，選擇出下列的要求：

```
# - 1. filtered by first column > 20?
# - 2. filtered by first column + second column > 50
# - 3. filtered by first column < 30 or second column > 30
# - 4. filtered by total sum of row > 100
```

In [ ]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

In [ ]:
# 參考解答

# - 1. filtered by first column > 20?

df.loc[df[0] > 20]
df[df[0] > 20]

# - 2. filtered by first column + second column > 50

df[df[0] + df[1] > 50]
df.loc[df[0] + df[1] > 50]

# - 3. filtered by first column < 30 or second column > 30

df[np.logical_or(df[0] < 30, df[1] > 30)]
df[(df[0] < 30) | (df[1] > 30)]

# - 4. filtered by total sum of row > 100

df[df[0] + df[1] + df[2] + df[3] > 100]
df[df.sum(axis=1) > 100]